name: lab3
description: A Flutter project for Ara Optical Center.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.12
  http: ^0.13.4
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.8
  ndialog: ^4.1.0
  image_picker: ^0.8.4+5
  image_cropper: ^1.4.1
  flutter_speed_dial: ^5.0.0+1
  curved_navigation_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
  fonts:
    - family: League Spartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.otf
